packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": "^24.1.0"
  "dotenv": "^17.2.1"
  "eslint": "^9.32.0"
  "prettier": "^3.6.2"
  "ts-node": "^10.9.2"
  "tsc-alias": "^1.8.16"
  "tsconfig-paths": "^4.2.0"
  "typescript": "^5.9.2"